services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    
    volumes:
      - ./mongodb:/data/db

    networks:
      - backend
    
    restart: always


networks:
  backend: